# Generated by Django 3.1.2 on 2021-01-31 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('sign', models.CharField(max_length=32, verbose_name='标识')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='LdapConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('host', models.CharField(max_length=128, verbose_name='地址')),
                ('admin_dn', models.CharField(max_length=128, verbose_name='管理员DN')),
                ('admin_password', models.CharField(max_length=128, verbose_name='管理员密码')),
                ('member_base_dn', models.CharField(max_length=128, verbose_name='用户基础DN')),
            ],
            options={
                'db_table': 'ldap_config',
            },
        ),
        migrations.CreateModel(
            name='ModModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='模块名')),
                ('sign', models.CharField(max_length=32, verbose_name='唯一标识')),
                ('rank', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'db_table': 'mod',
            },
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='权限名')),
                ('typ', models.SmallIntegerField(choices=[(10, '操作权限'), (20, '数据权限')], verbose_name='类型')),
                ('sign', models.CharField(db_index=True, max_length=128, verbose_name='唯一标识')),
                ('rank', models.IntegerField(verbose_name='排序')),
                ('mod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.modmodel')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='角色名')),
                ('typ', models.IntegerField(choices=[(10, '系统角色'), (20, '普通角色')], default=20, verbose_name='类型')),
                ('sign', models.CharField(max_length=32, verbose_name='标识')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('username', models.CharField(db_index=True, max_length=128, verbose_name='账户')),
                ('password', models.CharField(default=None, max_length=256, null=True, verbose_name='密码')),
                ('name', models.CharField(default='', max_length=128, verbose_name='姓名')),
                ('email', models.CharField(default='', max_length=128, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(default='', max_length=64, null=True, verbose_name='联系方式')),
                ('status', models.IntegerField(choices=[(10, '正常'), (20, '禁用')], default=10, verbose_name='状态')),
                ('typ', models.SmallIntegerField(choices=[(10, '标准用户'), (20, 'LDAP用户')], default=10, verbose_name='类型')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RoleUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rolemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usermodel')),
            ],
            options={
                'db_table': 'role_user',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.permissionmodel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rolemodel')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='RoleModModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.modmodel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rolemodel')),
            ],
            options={
                'db_table': 'role_mod',
            },
        ),
        migrations.CreateModel(
            name='DepartmentUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dt_update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('typ', models.SmallIntegerField(choices=[(10, '部门负责人'), (20, '普通成员')], default=20, verbose_name='类型')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.departmentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.usermodel')),
            ],
            options={
                'db_table': 'department_user',
            },
        ),
    ]
