# Generated by Django 3.1.2 on 2021-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='code',
            field=models.SmallIntegerField(choices=[(10, '标准用户'), (20, 'LDAP用户')], default=10, verbose_name='用户编号'),
        ),
    ]
